name: machinelearning
channels:
  - conda-forge
dependencies:
  # general numerics
  - libblas=*=*mkl
  - numpy
  - scipy
  - cython
  - xarray
  - sympy
  # machine learning
  - scikit-learn
  - cudatoolkit=11.2*
  - pytorch=1.12.1=*cuda112*
  - torchvision
  - gpytorch
  - botorch=0.7*
  - ax-platform=0.2*
  - blitz-bayesian-pytorch
  # plotting
  - matplotlib-base=3.6*
  - ipympl  # interactive plotting in jupyterlab
  - ipywidgets
  # serialization
  - protobuf
  - cloudpickle
  - dill
  # parallell computing
  - h5py
  - deepdish
  - zarr
  - dask
  # laser-plasma simulation
  - openpmd-api~=0.14.0
  # other
  - scikit-image
  - pandas=1.4*  # https://github.com/Epistimio/orion/issues/999
  - seaborn
  - sqlalchemy
  - pytables
  - xlrd
  - patsy
  - statsmodels
  - numba
  - bottleneck
  - numexpr
  # jupyter tools and extensions
  - papermill
  - widgetsnbextension

